exclude:
 - z__sh-scripts/
 - z__bat-scripts/
 - LICENSE.md
 - README.md
 - .gitignore
 
defaults:
  - scope:
      path: "icons/1_Primary"
    values:
      image: true
      is_primary: true
  - scope:
      path: "icons/2_Variations"
    values:
      image: true
      is_variation: true
  - scope:
      path: "icons/3_Generic"
    values:
      image: true
      is_generic: true

sass:
  style: compressed
