exclude:
 - .___get_icons.bat
 - .___start_jekyll_server.bat
 - LICENSE.md
 - README.md
 
defaults:
  - scope:
      path: "icons/1_Primary"
    values:
      image: true
      is_primary: true
  - scope:
      path: "icons/2_Variations"
    values:
      image: true
      is_variation: true
  - scope:
      path: "icons/3_Generic"
    values:
      image: true
      is_generic: true
  - scope:
      path: "icons/4_Outdated"
    values:
      image: true
      is_outdated: true

sass:
  style: compressed